version: '3.8'
services:
  app:
    container_name: fastify_backend
    image: 'calvez/fastify_backend:0.0.1'
    build:
      context: .
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: 'postgres:10.4'
    container_name: fastify-app-postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
    env_file: .env
    volumes:
      - fastify_volume:/var/lib/postgres/data
volumes:
  fastify_volume: {}
